data<-read.table("charles.txt", header=FALSE, sep="")
colnames(data)<-c("year","Airy","Charleston")
attach(data)
plot(Airy,Charleston,xlab="Mount Airy Avg Summer Temp", ylab="Charleston Avg Summer Temp")
result<-lm(Charleston~Airy)
abline(result)
summary(result)
cor(Airy,Charleston)
